### ISSUE TITLE
system_tests_topology_disposition AssertionError: 'No confirmed kill on connector.' is not None

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#612] opened 2022-07-15 21:11 UTC
There has been multiple failing jobs on this test recently, for example https://github.com/skupperproject/skupper-router/runs/7363684932?check_suite_focus=true#step:28:1282

```
35: __________________________________________________ TopologyDispositionTests.test_01_delete_spurious_connector __________________________________________________
35: 
35: self = <tests.system_tests_topology_disposition.TopologyDispositionTests testMethod=test_01_delete_spurious_connector>
35: 
35:     def test_01_delete_spurious_connector(self):
35:         name = 'test_01'
35:         if self.skip[name] :
35:             self.skipTest("Test skipped during development.")
35:         test = DeleteSpuriousConnector(name,
35:                                        self.client_addrs,
35:                                        'closest/01',
35:                                        self.client_addrs['D']
35:                                        )
35:         test.run()
35: >       self.assertIsNone(test.error)
35: E       AssertionError: 'No confirmed kill on connector.' is not None
35: 
35: /home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_tests_topology_disposition.py:363: AssertionError
```

**Comment by jiridanek** [comment] 2022-07-21 10:13
https://github.com/jiridanek/skupper-router/runs/7446693166?check_suite_focus=true#step:10:3058

**Comment by kgiusti** [comment] 2022-07-22 16:53
Seen again on main: TopologyDispositionTests::test_01_delete_spurious_connector - AssertionError: 'No confirmed kill on connector.' is not None

**Comment by kgiusti** [comment] 2022-07-22 16:54
Related: https://github.com/skupperproject/skupper-router/issues/450

#450

**Comment by kgiusti** [comment] 2022-07-25 12:45
Debugged this - test fails due to exiting too soon.
Test scenario:
Send 13 messages, delete connector, wait for delete response, continue to send up to 30 message.

Bug: the delete response comes after the 30 messages have transferred.  That causes the test to fail.

**Closed** 2022-07-26 19:55 UTC
