### ISSUE TITLE
adaptor buffer leak in system_tests_http2

### ISSUE THREAD

**Issue by ganeshmurthy** [skupperproject/skupper-router#741] opened 2022-09-27 13:03 UTC
```
 self = <system_test.Tester object at 0x7f14328a1d80>

    def teardown(self):
        """Clean up (tear-down, stop or close) objects recorded via cleanup()"""
        self.cleanup_list.reverse()
        errors = []
        for obj in self.cleanup_list:
            try:
                for method in ["teardown", "tearDown", "stop", "close"]:
                    cleanup = getattr(obj, method, None)
                    if cleanup:
                        cleanup()
                        break
            except Exception as exc:
                errors.append(exc)
        if errors:
>           raise RuntimeError("Errors during teardown: \n\n%s" % "\n\n".join([str(e) for e in errors]))
E           RuntimeError: Errors during teardown: 
E           
E           Process 3349 (name=http2-test-router) error: returned error code -6
E           skrouterd -c http2-test-router.conf -I /home/runner/work/skupper-router/skupper-router/skupper-router/python
E           /__w/skupper-router/skupper-router/skupper-router/build/tests/system_test.dir/tests/system_tests_http2/Http2TestOneEdgeRouter/setUpClass/http2-test-router-58.cmd
E           >>>>
E           ERROR: Aborted due to unexpected alloc pool leak of type 'qd_adaptor_buffer_t'
E           Fatal Python error: Aborted
E           
E           Current thread 0x00007fb66ec5c3c0 (most recent call first):
E             <no Python frame>
E           <<<<

/home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_test.py:1036: RuntimeError
---------------------------------------------------------------------- Captured log call -----------------------------------------------------------------------
INFO     proton:_reactor.py:1053 Connecting to Url('amqp://0.0.0.0:29724')...
INFO     proton:_reactor.py:1091 Connected to 0.0.0.0
---------------------- generated xml file: /__w/skupper-router/skupper-router/skupper-router/build/tests/junitxmls/system_tests_http2.xml ----------------------
=================================================================== short test summary info ====================================================================
ERROR ::Http2TestOneEdgeRouter::test_zzz_http_connector_delete - RuntimeError: Errors during teardown: 
=========================================================== 93 passed, 1 error in 282.02s (0:04:42) ============================================================
```

https://github.com/skupperproject/skupper-router/actions/runs/3135699596/jobs/5091692358#step:29:2140

**Comment by jiridanek** [comment] 2022-09-27 13:21
* Duplicate of https://github.com/skupperproject/skupper-router/issues/714

**Closed** 2022-09-27 13:30 UTC
