### ISSUE TITLE
system_tests_tcp_adaptor TcpLiteCutthroughAbortTest failing

### ISSUE THREAD

**Issue by ganeshmurthy** [skupperproject/skupper-router#1452] opened 2024-03-22 18:17 UTC
```
 =================================== FAILURES ===================================
____________ TcpLiteCutthroughAbortTest.test_aborted_streaming_link ____________

self = <tests.system_tests_tcp_adaptor.TcpLiteCutthroughAbortTest testMethod=test_aborted_streaming_link>

    def test_aborted_streaming_link(self):
        test = FakeClientStreamAborter(self.e_address, self.van_address, self.logger)
        test.run()
>       self.assertIsNone(test.error)
E       AssertionError: 'Timeout Expired' is not None

/home/gmurthy/actions-runner/_work/skupper-router/skupper-router/skupper-router/tests/system_tests_tcp_adaptor.py:2898: AssertionError
```
https://github.com/skupperproject/skupper-router/actions/runs/8392267222/job/22984523824#step:18:16160

**Comment by kgiusti** [comment] 2024-03-28 13:46
@ganeshmurthy could this be a duplicate of #1293

**Comment by kgiusti** [comment] 2024-03-28 13:49
Actually I retract the last comment - on further examination I think this is a flakey test. Looks like the test messaging handler state machine can miss the abort state.

**Closed** 2024-05-01 15:04 UTC
Labels: bug
