### ISSUE TITLE
Http1AdaptorManagementTest.test_01_delete_active_connector failure

### ISSUE THREAD

**Issue by ganeshmurthy** [skupperproject/skupper-router#443] opened 2022-05-06 15:04 UTC
```
 /home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_tests_http1_adaptor.py:250: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Qdrouterd: returncode: None args: ['skrouterd', '-c', 'HTTP1MgmtTestInterio...>, address = 'closest/http1Service', retry_kwargs = {}
check = <function Qdrouterd.wait_address_unsubscribed.<locals>.check at 0x7f92ee9ed000>, @py_assert3 = None
@py_format5 = 'assert None\n{None = retry(<function Qdrouterd.wait_address_unsubscribed.<locals>.check at 0x7f92ee9ed000>, **{})\n}'

    def wait_address_unsubscribed(self, address, **retry_kwargs):
        """
        Block until address has no subscribers
        """
        a_type = 'io.skupper.router.router.address'
    
        def check():
            addrs = self.management.query(a_type).get_dicts()
            rc = [a for a in addrs if a['name'].endswith(address)]
            count = 0
            for a in rc:
                count += a['subscriberCount']
                count += a['remoteCount']
    
            return count == 0
>       assert retry(check, **retry_kwargs)
E       assert None
E        +  where None = retry(<function Qdrouterd.wait_address_unsubscribed.<locals>.check at 0x7f92ee9ed000>, **{})

/home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_test.py:744: AssertionError
-------------------------------------------------------------------- Captured log teardown ---------------------------------------------------------------------
INFO     proton:_reactor.py:1105 Disconnected, already closed
INFO     proton:_reactor.py:1105 Disconnected, already closed
------------------ generated xml file: /__w/skupper-router/skupper-router/skupper-router/build/tests/junitxmls/system_tests_http1_adaptor.xml ------------------
=================================================================== short test summary info ====================================================================
FAILED ::Http1AdaptorManagementTest::test_01_delete_active_connector - assert None
=========================================================== 1 failed, 27 passed in 365.67s (0:06:05) ===========================================================
```

https://github.com/skupperproject/skupper-router/runs/6324436771?check_suite_focus=true#step:26:5123

**Comment by kgiusti** [comment] 2022-05-31 20:00
Duplicate of #203

**Closed by kgiusti** 2022-05-31 20:00 UTC
Labels: bug
