### ISSUE TITLE
Leak Sanitizer errors when router exits due to port-conflict

### ISSUE THREAD

**Issue by ted-ross** [skupperproject/skupper-router#156] opened 2022-03-10 16:43 UTC
If the router is started and there's another router using the same listener port, the new router shuts down immediately.  When this happens a number of Leak Sanitizer errors is raised.

**Comment by jiridanek** [comment] 2022-03-10 16:53
Is this duplicate of https://github.com/skupperproject/skupper-router/issues/116 or is the report different from the log pasted into the top comment there.

**Comment by ted-ross** [comment] 2022-03-11 14:08
I believe this is different.  This issue has nothing to do with the tests.

**Comment by jiridanek** [comment] 2022-03-11 14:13
Router did exit due to port-conflict in https://github.com/skupperproject/skupper-router/issues/116, that is the similarity I noticed.

**Comment by ted-ross** [comment] 2022-03-11 14:19
The sanitizer issues are probably the same, but the bugs are different.  In #116, the bug is that there was a port conflict.  In this bug, the port conflict is assumed, and the shutdown leaks are unexpected.  I'll note that this issue is pretty low priority.

**Comment by kgiusti** [comment] 2022-04-06 19:02
There are a bunch of shutdown-related leaks in the router. For leaks like this that are not release blockers let's capture them in this feature request: #293 so we can be sure these issues are fixed by the updated shutdown feature

**Closed by kgiusti** 2022-04-06 19:02 UTC
Labels: bug, P2
