### ISSUE TITLE
:Http2TestTlsTwoRouter::test_head_request_no_alpn_no_http2_prior_knowledge failure

### ISSUE THREAD

**Issue by kgiusti** [skupperproject/skupper-router#924] opened 2023-01-31 14:34 UTC
https://github.com/skupperproject/skupper-router/actions/runs/4052251516/jobs/6971460083#step:30:3307

```
62: ___________________________________________ Http2TestTlsTwoRouter.test_head_request_no_alpn_no_http2_prior_knowledge ___________________________________________
62: 
62: self = <tests.system_tests_http2_tls.Http2TestTlsTwoRouter testMethod=test_head_request_no_alpn_no_http2_prior_knowledge>
62: 
62:     @unittest.skipIf(skip_test(), "Python 3.7 or greater, Quart 0.13.0 or greater and curl needed to run http2 tests")
62:     # Tests the HTTP2 head request without APLN and without http2-prior-knowledge
62:     def test_head_request_no_alpn_no_http2_prior_knowledge(self):
62:         # Run curl 127.0.0.1:port --head --no-alpn
62:         # In this test, we do not use curl's --http2-prior-knowledge flag but instead use the --no-alpn flag.
62:         # This means that curl client will not offer an ALPN protocol at all. The router (server) sends back 'h2'
62:         # in its ALPN response which is ignored by the curl client.
62:         # The TLS handshake is successful and curl receives a http2 settings frame from the router which it does
62:         # not understand. Hence it complains with the error message
62:         # 'Received HTTP/0.9 when not allowed'
62:         address = self.router_qdra.http_addresses[0]
62:         _, out, err = self.run_curl(address,
62:                                     args=self.get_all_curl_args(['--head']),
62:                                     http2_prior_knowledge=False,
62:                                     no_alpn=True, assert_status=False)
62: >       self.assertIn('Received HTTP/0.9 when not allowed', err)
62: E       AssertionError: 'Received HTTP/0.9 when not allowed' not found in '  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\n  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\ncurl: (8) Weird server reply\n'
62: 
62: /home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_tests_http2_tls.py:230: AssertionError
```

**Comment by ganeshmurthy** [comment] 2023-02-03 16:23
This is a duplicate of https://github.com/skupperproject/skupper-router/issues/939
I already used #939 in my PR, so I am closing this one

**Closed by ganeshmurthy** 2023-02-03 16:23 UTC
