### ISSUE TITLE
system_tests_two_routers KeyError: 'adminStatus'

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#321] opened 2022-04-11 20:03 UTC
https://github.com/jiridanek/skupper-router/runs/5978454315?check_suite_focus=true#step:26:851

looks like random flaky fail

```
28:                 if event.message.properties['statusDescription'] != 'OK':
28:                     error = "Expected statusDescription to be OK but instead got %s" % \
28:                             event.message.properties['statusDescription']
28: >               if event.message.body['adminStatus'] != self.deleted_admin_status:
28: E               KeyError: 'adminStatus'
28: 
28: /home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_tests_two_routers.py:484: KeyError
```

**Comment by jiridanek** [comment] 2022-04-11 22:52
https://github.com/jiridanek/skupper-router/runs/5976545992?check_suite_focus=true#step:26:849

**Comment by ganeshmurthy** [comment] 2022-04-20 19:22
It looks like the `event.message.properties['statusDescription']` was not OK. There was a problem with the request but I am not sure what the problem is. That is why `event.message` did not have a body. The following if statement should be an elif statement. That way we can see the actual error

**Comment by ganeshmurthy** [comment] 2022-04-26 19:55
I am going to close this issue. When the real error shows up, we will open a new issue for it.

**Closed by ganeshmurthy** 2022-04-26 19:55 UTC
Labels: bug, test-bug
